[build]
release = true
filehash = false

[clean]
cargo = true

[watch]
watch = ["./index.html", "./tailwind.config.js", "./src/", "./assets/"]

[[hooks]]
stage = "pre_build"
command = "bash"
command_arguments = ["-c", "./tailwindcss -o ./style.css --minify"]
