name: CI

on: [push, pull_request]

permissions:
  contents: read
  pages: write
  id-token: write

runs-on: ubuntu-latest

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  setup:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        components: rustfmt, clippy
    - name: Install cargo-leptos
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: --locked cargo-leptos
  test:
    needs: setup
    - name: Test
      uses: actions-rs/cargo@v1
      with:
        command: test
  lint:
    needs: setup
    steps:
      - name: Lint
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
  format:
    needs: setup
    steps:
      - name: Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
  build:
    needs: test
    steps:
      - name: Install cargo-leptos
        uses: actions-rs/cargo@v1
        with:
          command: leptos
          args: build --release
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3
      - name: Upload build artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: './target/site'
      - name: Deploy website
        id: deployment
        uses: actions/deploy-pages@v2