name: CI

on: [push, pull_request]

permissions:
  contents: read
  pages: write
  id-token: write

runs-on: ubuntu-latest

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  test:
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt, clippy
          override: true
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: Lint
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
      - name: Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
  build:
    steps:
      - name: Install cargo-leptos
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --locked cargo-leptos
      - name: Install cargo-leptos
        uses: actions-rs/cargo@v1
        with:
          command: leptos
          args: build --release
  deploy:
    needs: [test, build]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3
      - name: Upload build artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: './dist'
      - name: Deploy website
        id: deployment
        uses: actions/deploy-pages@v2