name: Deploy Website

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run deployment script
        run: |
          chmod +x ./deploy.sh
          ./deploy.sh